version: '3.8'

services:
  backend:
    build:
      context: .  # Root directory as build context
      dockerfile: backend/Dockerfile
    container_name: ecom_ai_backend
    ports:
      - "8000:8000"
    environment:
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_RAW_SCHEMA=${SNOWFLAKE_RAW_SCHEMA}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

  frontend:
    build: ./frontend
    container_name: ecom_ai_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    name: ecom_ai_network